[workspace]
resolver = "1"
members = [
  "enum_variant_name",
  "logger",
  "mem",
  "networking",
  "random",
  "threading",
  "time",
  "math",
]

[workspace.dependencies]
serde = "1.0.217"
log = {version = "0.4.20", features = ["std"] }
